name: OpenVPN Installation
on:
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install My Application
      run: |
        # Replace 'your-package-name.deb' with the actual name of your .deb file
        sudo dpkg -i openvpn_2.4.12-0ubuntu0.20.04.1_amd64.deb
        sudo apt-get install -f  # Install dependencies

    - name: Verify installation
      run: |
        # Add any verification steps here, for example:
        openvpn --version  # Replace with the actual command to check the installed version
