name: OpenVPN Installation
on:
   workflow_dispatch:
   
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name : Install VPN
        run : |
          sudo apt install apt-transport-https
          sudo wget https://swupdate.openvpn.net/repos/openvpn-repo-pkg-key.pub
          sudo apt-key add openvpn-repo-pkg-key.pub
          sudo wget -O /etc/apt/sources.list.d/openvpn3.list https://swupdate.openvpn.net/community/openvpn3/repos/openvpn3-jammy.list
          sudo apt update
          sudo apt install openvpn3
          pwd
          cd /home/runner/work/cicd-devops/cicd-devops
          ls

      - name : Create Directory
         run: |
           mkdir -p cicd-devops

      - name: Copy files to repository
        run: |
          cp -R /home/runner/work/cicd-devops/cicd-devops/* cicd-devops/

      - name: Commit and push changes
        run: |
           cd cicd-devops
           git config --global user.email "sijinthomaspalliyady@gmail.com"
           git config --global user.name "Sijin Thomas"
           git add .
           git commit -m "Copy artifacts from GitHub Actions"
           git push
